VERSION 1.0 CLASS
BEGIN
MultiUse = -1  'True
END
Attribute VB_Name = "ITemplateCloner"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'namespace=vba-files/competition/modules/loader/cloner
Option Explicit

Public Sub Clone(DestinationFile As String)
End Sub

' (Template Start) ============================================================
' Implements ITemplateCloner

' Private Sub ITemplateCloner_Clone(DestinationFile As String)
' End Sub

' (Template End) ==============================================================
